#this is a reg map definition for MP6570
# uint16_t (\w+):(\d+);

[config]
headers = ["<cstdint>", "core/io/regs.hpp"]
file_name = "MP6570_Regs.hpp"
namespace_name = "ymd::drivers"
frontend_type = 1.0
backend_type = 1.0

[CTRL1]
address = 0x05
width = 16
docu = '''
    控制寄存器1
    '''

[CTRL1.nstep]
bits = 0.9
docu = '''
    Defines the reference step value LSBs with each clock input. 
    With clock input mode, the reference moves forward 4*NSTEP 
    LSBs with each clock input. Therefore, the steps number per 
    round is 65536/(4*NSTEP).
    With the digital and PWM input in speed mode, the gain 
    coefficient is 1 when setting NSTEP[0] with 0. The gain 
    coefficient is 8 when setting NSETEP[0] with 1.
    '''