#ifndef __FWWB_ENUMS_HPP__

#define __FWWB_ENUMS_HPP__

namespace FWWB{
enum class Command:uint8_t{
    GET_HP = 0,
    SET_HP,
    GET_WEIGHT,
    SET_WEIGHT,
    GET_DAMAGE_TIME,

    DEFENSE_SET_ID = 0x20,
    DEFENSE_GET_ID,
    DEFENSE_GET_TOTAL,

    ATTACK_SET_ID = 0x50,
    ATTACK_GET_ID,
    ATTACK_SET_TOWARD,
    ATTACK_GET_TOWARD,
    ATTACK_SET_PITCH,
    ATTACK_GET_PITCH,
    ATTACK_SET_YAW,
    ATTACK_GET_YAW,
    ATTACK_SHOT,

    CHASSIS_SET_ID = 0x60,
    CHASSIS_GET_ID,
    CHASSIS_SET_MOVE,
    CHASSIS_GET_MOVE,
    CHASSIS_SET_OMEGA,
    CHASSIS_GET_OMEGA,
    CHASSIS_GET_ODO,
    CHASSIS_GET_POS,

    CHASSIS_SET_MODE = CHASSIS_SET_ID + 0x0f,

    RST = 0x70,
    INACTIVE,
    ACTIVE,
    SYNC,
    SCAN,
    REGISTER_NODEID,
    MANU_ID,
    POWER_ON = 0x7e,
    OUTBOUND = 0x7f
};

};


#endif