#ifndef __FWWB_ENUMS_HPP__

#define __FWWB_ENUMS_HPP__

namespace FWWB{
enum class Command:uint8_t{
    GET_HP = 0,
    SET_HP,
    GET_WEIGHT,
    SET_WEIGHT,
    GET_DAMAGE_TIME,

    DEFENSE_SET_ID = 0x20,
    DEFENSE_GET_ID,
    DEFENSE_GET_TOTAL,

    ATTACK_SET_ID = 0x50,
    ATTACK_GET_ID,
    ATTACK_SET_TOWARD,
    ATTACK_GET_TOWARD,
    ATTACK_SET_PITCH,
    ATTACK_GET_PITCH,
    ATTACK_SET_YAW,
    ATTACK_GET_YAW,
    ATTACK_SHOT,

    PEDESTRIAN_SET_ID = 0x60,
    PEDESTRIAN_GET_ID,
    PEDESTRIAN_SET_MOVE,
    PEDESTRIAN_GET_MOVE,
    PEDESTRIAN_SET_OMEGA,
    PEDESTRIAN_GET_OMEGA,
    PEDESTRIAN_GET_ODO,
    PEDESTRIAN_GET_POS,


    RST = 0x70,
    INACTIVE,
    ACTIVE,
    SYNC,
    SCAN,
    REGISTER_NODEID,

    SET_MODE = 0x7c,
    MANU_ID = 0x7d,
    POWER_ON = 0x7e,
    OUTBOUND = 0x7f
};

};


#endif